app/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("core.urls")),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

core/urls.py
from django.urls import path

from core import views

app_name = "core"

urlpatterns = [
    path("", views.index, name="index"),
    path("post/", views.index_post, name="index_post"),
]

core/models.py
from django.db import models


class Organizer(models.Model):
    """Organizer model."""

    name = models.CharField(max_length=100)
    email = models.EmailField()
    phone = models.CharField(max_length=20)
    organization = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Event(models.Model):
    """Event model."""

    title = models.CharField(max_length=200)
    description = models.TextField()
    start_date = models.DateTimeField()
    end_date = models.DateTimeField()
    location = models.CharField(max_length=200)
    organizer = models.ForeignKey(
        Organizer, on_delete=models.CASCADE, related_name="events"
    )
    is_active = models.BooleanField(default=True)
    is_deleted = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title


class Attendee(models.Model):
    """Attendee model."""

    name = models.CharField(max_length=100)
    email = models.EmailField()
    phone = models.CharField(max_length=20)
    event = models.ForeignKey(Event, on_delete=models.CASCADE, related_name="attendees")

    def __str__(self):
        return self.name


class Ticket(models.Model):
    """Ticket model."""

    TICKET_TYPES = [
        ("Regular", "Regular"),
        ("VIP", "VIP"),
        ("Premium", "Premium"),
    ]
    event = models.ForeignKey(Event, on_delete=models.CASCADE, related_name="tickets")
    attendee = models.ForeignKey(
        Attendee, on_delete=models.CASCADE, related_name="tickets"
    )
    ticket_type = models.CharField(max_length=20, choices=TICKET_TYPES)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    quantity = models.IntegerField()
    purchase_date = models.DateTimeField()
    is_paid = models.BooleanField(default=False)
    is_deleted = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.ticket_type} Ticket for {self.event.title}"


class Image(models.Model):
    """Image model."""

    def event_image_upload(instance, filename):
        return f"event_image/{instance.event.title}/{filename}"

    image = models.ImageField(
        upload_to=event_image_upload,
        height_field=None,
        width_field=None,
        max_length=None,
    )
    event = models.ForeignKey(Event, on_delete=models.CASCADE, related_name="images")

    def __str__(self):
        return self.event.title

users/models.py
from django.contrib.auth.base_user import BaseUserManager
from django.contrib.auth.models import AbstractUser
from django.db import models


class NewUserManager(BaseUserManager):
    def create_user(self, email, password, **extra_fields):
        normalized_email = self.normalize_email(email)
        user = self.model(email=normalized_email, **extra_fields)
        user.set_password(password)
        user.save()
        return user

    def create_superuser(self, email, password, **extra_fields):
        extra_fields.setdefault("is_staff", True)
        extra_fields.setdefault("is_superuser", True)
        extra_fields.setdefault("is_active", True)

        if extra_fields.get("is_staff") is not True:
            raise ValueError("Superuser must have is_staff=True.")
        if extra_fields.get("is_superuser") is not True:
            raise ValueError("Superuser must have is_superuser=True.")
        return self.create_user(email, password, **extra_fields)


class User(AbstractUser):
    username = None
    email = models.EmailField(unique=True)

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    objects = NewUserManager()

    def __str__(self):
        return self.email

    @property
    def admin_full_name(self):
        return f"{self.first_name} {self.last_name}"

core/views.py
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render
from django.views.decorators.http import require_GET, require_POST
from django_htmx.middleware import HtmxDetails


class HtmxHttpRequest(HttpRequest):
    htmx: HtmxDetails


@require_GET
def index(request: HtmxHttpRequest) -> HttpResponse:
    return render(request, "home.html")


@require_POST
def index_post(request: HtmxHttpRequest) -> HttpResponse:
    email = request.POST.get("email")
    return render(request, "home.html#test-partial", {"email": email})

users/views.py
from django.shortcuts import render

# Create your views here.

templates/components/card.html
<li class="flex py-4">
    <div class="ml-3">{{ children }}</div>
</li>

templates/home.html
{% load static %}

<!doctype html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="stylesheet" href="{% static 'styles/style.css' %}" />
        <script src="{% static 'htmx.min.js' %}" defer="defer"></script>
        <script src="{% static 'debug.js' %}" defer="defer"></script>
        <title>Document</title>
    </head>

    <body>
        {% partialdef test-partial %}
            {% if email %}
                {% #card %}
                <p class="text-sm text-gray-500">{{ email|default:"" }}</p>
                {% /card %}
            {% endif %}
        {% endpartialdef %}

        <ul role="list" id="card" class="divide-y divide-gray-200">
            {% partial test-partial %}
        </ul>

        <div>
            <label for="email" class="block text-sm font-medium leading-6 text-gray-900">Email</label>
            <div class="relative mt-2 rounded-md shadow-sm">
                <input
                    type="email"
                    name="email"
                    id="email"
                    class="block w-auto rounded-md border-0 py-1.5 pr-10 text-indigo-900 ring-1 ring-inset ring-indigo-300 placeholder:text-indigo-300 focus:ring-2 focus:ring-inset focus:ring-indigo-500 sm:text-sm sm:leading-6"
                    placeholder="you@example.com"
                    aria-invalid="true"
                />
            </div>
        </div>

        <button
            hx-post="{% url 'core:index_post' %}"
            hx-headers='{"X-CSRFToken": "{{ csrf_token }}"}'
            hx-target="#card"
            hx-trigger="click"
            hx-swap="beforeend"
            hx-include="[name='email']"
        >
            Add
        </button>
    </body>
</html>